{{- if or .Values.secret .Values.secretLink -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
{{- if .Values.secret}}
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end}}
{{- if .Values.secretLink}}
stringData:
  {{- range $key, $val := .Values.secretLink }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end}}
{{- end}}
