
replicaCount: 1

image:
  repository: 478935270195.dkr.ecr.eu-north-1.amazonaws.com/cobalt
  tag: fe
  pullPolicy: Always

imagePullSecrets: [{
  name: registry-secret
}]

nameOverride: "cobaltfe"
fullnameOverride: "cobaltfe"

service:
  type: ClusterIP
  port: 80
  containerPort: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
  hosts:
    - host: cobalt.origamilab.ch
      path: /
      pathType: Prefix
  tls:
    - secretName: front-end-tls
      hosts:
        - cobalt.origamilab.ch

resources:
#  limits:
#    cpu: 500m
#    memory: 500Mi
#  requests:
#    cpu: 500m
#    memory: 500Mi

livenessProbe:
#  httpGet:
#    path: /
#    port: http
#    scheme: HTTP
#  initialDelaySeconds: 30
#  periodSeconds: 30
#  timeoutSeconds: 30
readinessProbe:
#  httpGet:
#    path: /
#    port: http
#    scheme: HTTP
#  initialDelaySeconds: 30
#  periodSeconds: 30
#  timeoutSeconds: 30

tolerations: []

affinity: {}

configmap: {}

secret: {}

secretLink: {}
