name: prod
on:
  workflow_dispatch
  # push:
  #   branches:
  #     - master

env:
  IMAGE: ${{ secrets.DOCKER_REGISTRY }}/front-end
  TAG: latest

jobs:
  deploy:
    environment:
      name: prod
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build -f Dockerfile.prod -t $IMAGE:$TAG .

      - name: Push image
        run: |
          docker login ${{ secrets.DOCKER_REGISTRY }} -u nologin -p ${{ secrets.SCW_SECRET_KEY }}
          docker push $IMAGE:$TAG

      - name: Deploy
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            helm uninstall front-end
            helm install front-end helm --namespace=default -f helm/values.prod.yaml
